// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hw struct {
	ID              string  `json:"id"`
	Type            string  `json:"type"`
	Manufacturer    string  `json:"manufacturer"`
	Series          string  `json:"series"`
	SerialNumber    string  `json:"serialNumber"`
	Bought          string  `json:"bought"`
	WarrantyExpires string  `json:"warrantyExpires"`
	User            *string `json:"user"`
	Department      *string `json:"department"`
}

type HwItem struct {
	ID              string  `json:"id"`
	Type            string  `json:"type"`
	Manufacturer    string  `json:"manufacturer"`
	Series          string  `json:"series"`
	SerialNumber    string  `json:"serialNumber"`
	Bought          string  `json:"bought"`
	WarrantyExpires string  `json:"warrantyExpires"`
	User            *string `json:"user"`
	Department      *string `json:"department"`
}
